### ISSUE TITLE
Hello Client

### ISSUE THREAD

**Issue by AngelOnFira** [Hack-The-Tunnels-8/hack-the-tunnels-team-tonka-t#2]
## Description:

Checkout: `client/src/pages/Home/Home.tsx` to get started.

Add the text "Hello World" withing a [paragraph element (\<p\>)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) on the home page.

## Acceptance Criteria:

"Hello World" is displayed on the home page.

**Comment by Chenguku** [comment]
!review

**Comment by Nguyen-HanhNong** [comment]
!approve

**Comment by Nguyen-HanhNong** [comment]
!approve
